"""내보내기 라우터: PNG / SVG / PDF / 포트폴리오"""
import json
from typing import Optional
from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse
from pydantic import BaseModel

router = APIRouter()


class ExportRequest(BaseModel):
    ir_json: dict
    diagram_id: Optional[str] = None
    title: Optional[str] = "diagram"


class PortfolioRequest(BaseModel):
    ir_json: dict
    diagram_id: Optional[str] = None
    project_title: str
    period: Optional[str] = None
    role: Optional[str] = None
    team_size: Optional[str] = None
    tech_rationale: Optional[str] = None
    achievements: Optional[str] = None


@router.post("/png")
async def export_png(request: ExportRequest):
    """
    PNG 내보내기.
    실제 렌더링은 프론트엔드의 html-to-image가 담당.
    이 엔드포인트는 서버사이드 fallback용.
    """
    return {"message": "PNG 내보내기는 프론트엔드에서 html-to-image로 처리됩니다."}


@router.post("/portfolio")
async def export_portfolio(request: PortfolioRequest):
    """포트폴리오 HTML 생성"""
    try:
        from core.llm import get_llm_client
        client = get_llm_client()

        # 기술 스택 자동 추출
        ir = request.ir_json
        node_types = list({n.get("type", "") for n in ir.get("nodes", [])})
        cloud_groups = list({g.get("cloud", "") for g in ir.get("groups", []) if g.get("cloud")})

        # LLM으로 기술 개요 생성
        tech_desc = request.tech_rationale or ""
        if not tech_desc:
            response = client.chat.completions.create(
                model="deepseek-chat",
                messages=[{
                    "role": "user",
                    "content": f"""다음 인프라 아키텍처 JSON을 기반으로 포트폴리오용 기술 개요를 한국어로 3~4문장 작성하세요.
JSON IR: {json.dumps(ir, ensure_ascii=False)}
클라우드: {', '.join(cloud_groups)}
컴포넌트: {', '.join(node_types)}"""
                }],
            )
            tech_desc = response.choices[0].message.content

        # 간단한 HTML 포트폴리오 생성
        html = f"""<!DOCTYPE html>
<html lang="ko">
<head>
<meta charset="UTF-8">
<title>{request.project_title} - 포트폴리오</title>
<style>
  body {{ font-family: 'Noto Sans KR', sans-serif; max-width: 900px; margin: 0 auto; padding: 40px; }}
  h1 {{ color: #1a1a2e; }}
  .meta {{ color: #666; margin-bottom: 20px; }}
  .section {{ margin: 30px 0; padding: 20px; background: #f8f9fa; border-radius: 8px; }}
  .tech-stack {{ display: flex; flex-wrap: wrap; gap: 8px; }}
  .tech-tag {{ background: #e3f2fd; color: #1565c0; padding: 4px 12px; border-radius: 20px; font-size: 14px; }}
</style>
</head>
<body>
<h1>{request.project_title}</h1>
<div class="meta">
  {f"기간: {request.period}" if request.period else ""}
  {f" | 역할: {request.role}" if request.role else ""}
  {f" | 팀 규모: {request.team_size}" if request.team_size else ""}
</div>

<div class="section">
  <h2>기술 개요</h2>
  <p>{tech_desc}</p>
</div>

<div class="section">
  <h2>사용 기술 스택</h2>
  <div class="tech-stack">
    {' '.join(f'<span class="tech-tag">{t}</span>' for t in cloud_groups + node_types if t)}
  </div>
</div>

{f'<div class="section"><h2>성과 지표</h2><p>{request.achievements}</p></div>' if request.achievements else ""}

<p style="color:#999; font-size:12px; margin-top:40px;">Generated by ArchGen</p>
</body>
</html>"""

        return {"html": html, "tech_description": tech_desc}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
